// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvlsjcwgqrliqxwzobaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bHNqY3dncXJsaXF4d3pvYmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NDcwMDMsImV4cCI6MjA0OTEyMzAwM30.gdNR6O7c_NzFWaTY9MAoMZDX3PV01DQaVlxTLHVkAWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);